/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersPageRouteImport } from './routes/characters.$page'
import { Route as CharacterIdRouteImport } from './routes/character.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersPageRoute = CharactersPageRouteImport.update({
  id: '/characters/$page',
  path: '/characters/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character/$id': typeof CharacterIdRoute
  '/characters/$page': typeof CharactersPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character/$id': typeof CharacterIdRoute
  '/characters/$page': typeof CharactersPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character/$id': typeof CharacterIdRoute
  '/characters/$page': typeof CharactersPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/character/$id' | '/characters/$page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/character/$id' | '/characters/$page'
  id: '__root__' | '/' | '/character/$id' | '/characters/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterIdRoute: typeof CharacterIdRoute
  CharactersPageRoute: typeof CharactersPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$page': {
      id: '/characters/$page'
      path: '/characters/$page'
      fullPath: '/characters/$page'
      preLoaderRoute: typeof CharactersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterIdRoute: CharacterIdRoute,
  CharactersPageRoute: CharactersPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
